# 3. 연산

## 3-1. 산술연산

In [2]:
import numpy as np

In [3]:
# 1차원 배열
a = np.arange(1, 5) # 1~4
b = np.arange(5, 9) # 5~8

In [4]:
a, b

(array([1, 2, 3, 4]), array([5, 6, 7, 8]))

In [5]:
# shape이 같아야 함
a + b

array([ 6,  8, 10, 12])

In [6]:
a - b

array([-4, -4, -4, -4])

In [7]:
a * b

array([ 5, 12, 21, 32])

In [8]:
a / b

array([0.2       , 0.33333333, 0.42857143, 0.5       ])

In [68]:
# 2차원 배열
a = np.arange(1, 7).reshape(2, 3)
a

array([[1, 2, 3],
       [4, 5, 6]])

In [10]:
b = np.arange(7, 13).reshape(2, 3)
b

array([[ 7,  8,  9],
       [10, 11, 12]])

In [11]:
a + b

array([[ 8, 10, 12],
       [14, 16, 18]])

In [12]:
a - b

array([[-6, -6, -6],
       [-6, -6, -6]])

In [13]:
# 단순 곱셈 (이렇게는 안 쓰임)
a * b

array([[ 7, 16, 27],
       [40, 55, 72]])

In [14]:
a / b

array([[0.14285714, 0.25      , 0.33333333],
       [0.4       , 0.45454545, 0.5       ]])

### 행렬의 곱셈 (dot product)

In [69]:
b = np.arange(7, 13).reshape(3, 2)
b

array([[ 7,  8],
       [ 9, 10],
       [11, 12]])

In [70]:
a, b

(array([[1, 2, 3],
        [4, 5, 6]]),
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]]))

In [71]:
c = np.dot(a, b)
c

array([[ 58,  64],
       [139, 154]])

In [73]:
a.dot(b)

array([[ 58,  64],
       [139, 154]])

### 배열과 스칼라(숫자)와의 연산 (Broadcasting)

In [74]:
a = np.array([1, 2, 3])
a

array([1, 2, 3])

In [75]:
a + 3

array([4, 5, 6])

In [76]:
a - 3

array([-2, -1,  0])

In [77]:
a * 3

array([3, 6, 9])

In [78]:
a / 3

array([0.33333333, 0.66666667, 1.        ])

## 3-2. Aggregation 함수

### 1차원 배열

In [79]:
a = np.array([1, 2, 3, 4, 5])
a

array([1, 2, 3, 4, 5])

In [80]:
# max값 찾기
np.max(a)

5

In [81]:
# min값 찾기
np.min(a)

1

In [82]:
a.max(), a.min()

(5, 1)

In [83]:
# sum값 구하기
np.sum(a)

15

In [84]:
# 평균값 구하기
np.mean(a)

3.0

In [85]:
# 이상치(outlier)가 있는 경우 평균갑시 요 배열의 데이터를 잘 대표한다고 불 수 있을까?
b = np.array([1, 2, 100, 3, 4])
b

array([  1,   2, 100,   3,   4])

In [86]:
# 중앙값(median), 중위값
np.median(b)

3.0

In [87]:
# 데이터가 짝수개인 경우
b = np.array([1, 3, 5, 100])
np.median(b)

4.0

In [88]:
# 표준편차 (standard deviation)
np.std(a)

1.4142135623730951

### 2차원 배열

In [89]:
a = np.arange(1, 7).reshape(2, 3)
a

array([[1, 2, 3],
       [4, 5, 6]])

In [90]:
np.max(a), a.max()

(6, 6)

In [91]:
np.min(a), a.min()

(1, 1)

In [92]:
# 2차원 배열의 경우 axis를 주어 각 행과 열의 max값을 구할 수 있음
np.max(a, axis=0)  # 행(row)

array([4, 5, 6])

In [93]:
np.max(a, axis=1)  # 열(column)

array([3, 6])

In [94]:
np.min(a, axis=0)

array([1, 2, 3])

In [95]:
np.min(a, axis=1)

array([1, 4])

In [96]:
np.sum(a, axis=0)

array([5, 7, 9])

In [97]:
np.sum(a, axis=1)

array([ 6, 15])

In [98]:
a = np.array([1, 2, 3, 4, 5])
a

array([1, 2, 3, 4, 5])

In [113]:
# cumsum, corrcoef(상관계수) 구하기 # cumsum : 누적 계산
np.cumsum(a)

array([ 1,  3,  6, 10, 15], dtype=int32)

In [100]:
b = np.arange(1, 7).reshape(2, 3)
b

array([[1, 2, 3],
       [4, 5, 6]])

In [101]:
np.cumsum(b, axis=0)

array([[1, 2, 3],
       [5, 7, 9]], dtype=int32)

In [102]:
np.cumsum(b, axis=1)

array([[ 1,  3,  6],
       [ 4,  9, 15]], dtype=int32)

In [103]:
# corrcoef (상관계수)
# 키와 몸무게의 상관관계
h = [160, 165, 170, 180]
w = [47, 55, 70, 85]
np.corrcoef(h, w)

array([[1.        , 0.99040485],
       [0.99040485, 1.        ]])

In [104]:
ha = np.mean(h)
wa = np.mean(w)
ha, wa

(168.75, 64.25)

In [121]:
# squrt (제곱근)
a = np.sqrt(np.sum((h - ha)**2))
a

14.79019945774904

In [106]:
b = np.sqrt(np.sum((w - wa)**2))
b

29.098969053902923

In [107]:
c = np.sum((h - ha) * (w - wa))
c

426.25

In [108]:
r = c / (a * b)
r

0.990404850180661

## 비교 (Comparison)

In [109]:
a = np.array([1, 2, 3, 4, 5])
a

array([1, 2, 3, 4, 5])

In [110]:
a >= 3

array([False, False,  True,  True,  True])

In [111]:
a + 3

array([4, 5, 6, 7, 8])

In [112]:
a == 3

array([False, False,  True, False, False])